FROM golang:1.19 as build

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o server -ldflags="-w -s" cmd/example/main.go

FROM scratch

COPY --from=build /app/server /server

CMD ["/server"]