apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: raphaelmb/goserver
          ports:
            - containerPort: 8080
